### ISSUE TITLE
Bot Error

### ISSUE THREAD

**Issue by kwadwobro1** [codez0mb1e/BinanceBot#4]
![image](https://user-images.githubusercontent.com/9765196/117484841-8864e680-af5f-11eb-93c3-0f62a9d55aad.png)

**Comment by Hirogurimu** [comment]
hello can you help me make my bot

**Comment by codez0mb1e** [comment]
Looks like your local PC (or server) time and time of Binance's trade server have a significant difference (by default it is 1 second).

Firstly try to sync time with global time. And then set a higher value for `ReceiveWindow` variable ([here](../blob/master/src/BinanceBot.MarketBot.Console/Program.cs)).
